name: CI/CD Pipeline

on:
  push:
    branches: [main, secondary]
  pull_request:
    branches: [main, secondary]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x] # Define node versions to test against

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
        working-directory: ./ecom-frontend
      - name: Run lint
        run: npm run lint
        working-directory: ./ecom-frontend
      - name: Build
        run: npm run build
        working-directory: ./ecom-frontend
      - name: Run tests
        run: npm test
        working-directory: ./ecom-frontend
